code --install-extension ahinkle.laravel-model-snippets
code --install-extension amiralizadeh9480.laravel-extra-intellisense
code --install-extension beardedbear.beardedtheme
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension bradlc.vscode-tailwindcss
code --install-extension codingyu.laravel-goto-view
code --install-extension davidanson.vscode-markdownlint
code --install-extension dotjoshjohnson.xml
code --install-extension editorconfig.editorconfig
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension github.github-vscode-theme
code --install-extension gruntfuggly.todo-tree
code --install-extension hakcorp.php-awesome-snippets
code --install-extension liamhammett.inline-parameters
code --install-extension mikestead.dotenv
code --install-extension neilbrayfield.php-docblocker
code --install-extension onecentlin.laravel-blade
code --install-extension pkief.material-icon-theme
code --install-extension sainnhe.gruvbox-material
code --install-extension shufo.vscode-blade-formatter
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension vue.volar
code --install-extension wayou.vscode-todo-highlight
code --install-extension xabikos.javascriptsnippets